version: '3.8'

services:
  nest-app:
    image: node:18
    container_name: task-management-backend
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - '3001:3001'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: task-management
    command: ['npm', 'run', 'start:dev']
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: task-management
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
